### ISSUE TITLE
General report structure of Milestone 1

### ISSUE THREAD

**Issue by sgdkd** [UBC-MDS/group-2#7]
Hi Everyone,
I check the example Predicting breast cancer and summarize the final report structure like below.
Feel free to add any section by comment if you want to make the report better！
**Bold**-Writing part
_Italic_-Coding part

As required by expectation, I suggest each of us take at least 1 coding part AND 1 writing part.
**Add visualization/explanation if you want.**

- [x] **[Summary]**
- [x] **[Background Introduction]**
- [x] **[Data method]**
- [x] **[Analysis method]**
- [x] _[download data , read in data]_
- [x] _[EDA, **EDA summary**]_
- [x] _[preprocessor]_
- [x] _[parameter optimization]_
- [x] _[test score]_
- [x] **[Discussion, what to improve]**
- [x] **[References]**

**Comment by sgdkd** [comment]
I have a short meeting with Paramveer , and take some of tasks as below.

Paramveer - Make sure processed data is saved and do hyperparameter optimization by 2024-11-21 20:00.
Zoe - Finish writing background introduction and data method (if needed) and set up data preprocessor for model by 2024-11-21 23:59.

**Comment by sgdkd** [comment]
> I have a short meeting with Paramveer , and take some of tasks as below.
> 
> Paramveer - Make sure processed data is saved and do hyperparameter optimization by 2024-11-21 20:00. Zoe - Finish writing background introduction and data method (if needed) and set up data preprocessor for model by 2024-11-21 23:59.

I've done the mentioned parts!

**Comment by Psingh238** [comment]
We now just need to write the summary and add more references used for the resources used.
